const ShopActionTypes ={
FETCH_COLLECTION_REQUEST : 'FETCH_COLLECTION_REQUEST',
FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
FETCH_COLLECTION_FAIL: 'FETCH_COLLECTION_FAIL'
}



export default ShopActionTypes;